/**
  * Each new term in the Fibonacci sequence is generated by adding
  *  the previous two terms. By starting with 1 and 2,
  * the first 10 terms will be:
  *
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  * 
  * By considering the terms in the Fibonacci sequence whose values do 
  *  not exceed four million, find the sum of the even-valued terms.
  * 
  */

// 2 + 8 + 34 = 44; max 100
const evenFibonacciSum = (max) => {
  let perviousNum = 1;
  let nextNum = 2;
  let total = 0;
  let evenNumsSum = 2;
  let previousEvenNumSum = 0;
  let totalSum = 0;

  while (total < max) {
    total = perviousNum + nextNum;
    // console.log('even Numbers: ', evenNumsSum)

    if (total > max) {
      return evenNumsSum;
      // break;
    }

    if (total % 2 === 0) {
      evenNumsSum += total;
      console.log('Even number found: ', evenNumsSum)
    }

    perviousNum = nextNum;
    nextNum = total;
  }

  return evenNumsSum;

}

// evenFibonacciSum(10)


console.log(evenFibonacciSum(4000000))
